CREATE TABLE customer_transactions (
    transaction_key SERIAL PRIMARY KEY,
    customer_id         VARCHAR NOT NULL,
    first_name          VARCHAR,
    last_name           VARCHAR,
    full_name           VARCHAR,
    gender              VARCHAR,
    dob                 DATE,
    age                 INTEGER,
    email               VARCHAR,
    phone               VARCHAR,
    address             VARCHAR,
    city                VARCHAR,
    state               VARCHAR,
    zip_code            VARCHAR,
    credit_score        INTEGER,
    annual_income       DOUBLE PRECISION,
    employment_status   VARCHAR,
    account_open_date   DATE,
    account_type        VARCHAR,
    account_balance     DOUBLE PRECISION,
    transaction_id      VARCHAR NOT NULL,
    transaction_date    DATE,
    transaction_amount  DOUBLE PRECISION,
    transaction_type    VARCHAR,
    merchant_name       VARCHAR,
    merchant_category   VARCHAR,
    payment_method      VARCHAR,
    card_last_four      VARCHAR,
    card_type           VARCHAR,
    is_flagged          BOOLEAN,
    is_fraud            BOOLEAN,
    risk_score          DOUBLE PRECISION,
    notes               VARCHAR,
    internal_comments   VARCHAR,
    legacy_id           VARCHAR
);
